# Generated by go2rpm 1
%bcond_without check

# https://github.com/direnv/direnv
%global goipath         github.com/direnv/direnv
Version:                2.20.1

%gometa

%global common_description %{expand:
direnv augments existing shells with a new feature that can load and unload
environment variables depending on the current directory.}

%global golicenses      LICENSE.md
%global godocs          docs CHANGELOG.md README.md version.txt man/direnv-\\\
                        stdlib.1.md man/direnv.toml.1.md man/direnv.1.md

Name:           direnv
Release:        1%{?dist}
Summary:        Per-directory shell configuration tool

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

# Work around bug in markdown->man generation
# https://github.com/direnv/direnv/pull/113
Patch0:         direnv-fix-manpage.patch

BuildRequires:  golang(github.com/BurntSushi/toml)
BuildRequires:  golang(github.com/direnv/go-dotenv)

%description
%{common_description}

%gopkg

%prep
%goprep
%patch0 -p1

%build
%gobuild -o %{gobuilddir}/bin/direnv %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -m 0755 -vd         %{buildroot}%{_mandir}/man1
install -m 0644 -vp man/*.1 %{buildroot}%{_mandir}/man1

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.md
%doc docs CHANGELOG.md README.md version.txt
%{_bindir}/*
%{_mandir}/man1/*

%gopkgfiles

%changelog
* Wed Oct 30 2019 Ed Marshall <esm@logic.net> - 2.20.1-1
- Update to 2.20.1
- Update spec to latest Fedora go packaging guidelines

* Tue Aug 30 2016 Dominic Cleal <dominic@cleal.org> - 2.9.0-2
- Fix make call to use parallel flag macro
- Fix default values of EA/BRs when macros aren't defined

* Wed Jul 20 2016 Dominic Cleal <dominic@cleal.org> - 2.9.0-1
- Initial build for Fedora
